version: '2'
services:
  rancher-laravel-demo:
    image: philiplarsson/rancher-laravel-demo:latest
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
    environment:
      RELEASE_VERSION: "${RELEASE_VERSION}"
  laravel-demo-load-balancer:
    image: rancher/lb-service-haproxy:v0.9.1
    ports:
    - 80:80/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
      io.rancher.scheduler.global: 'true'

