version: '2'
services:
  rancher-laravel-demo:
    scale: 2
    start_on_create: true
  laravel-demo-load-balancer:
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - path: ''
        priority: 1
        protocol: http
        service: rancher-laravel-demo
        source_port: 80
        target_port: 2015
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
